name: pipline

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: .Net Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
          
      - name: Build project
        run: dotnet build --configuration Release --no-restore
        
        - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: ./out
          
  test:
    needs: build
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout repository
        uses: action/checkout@v2
       
      - name: build output
        uses: actions/download-artifact@v2
        with:
          name: build-output
          path: ./out
          
      - name: Tests
        run: dotnet test
      